# Generated by Django 5.1.2 on 2024-10-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_subject',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Тема поста'),
        ),
    ]
