# Generated by Django 5.1.2 on 2024-10-09 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_alter_user_nickname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='receiver',
        ),
        migrations.AddField(
            model_name='friendship',
            name='recipient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='friendship_recipient', to='messenger.user', verbose_name='Получатель заявки на дружбу'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_messages', to='messenger.user', verbose_name='Автор сообщения'),
        ),
        migrations.AlterField(
            model_name='message',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipient_messages', to='messenger.user', verbose_name='Получатель сообщения'),
        ),
    ]
